pip3.6 install google -q
pip3.6 install wikipedia -q
pip3.6 install pytz -q
pip3.6 install datetime -q
pip3.6 install nltk -q
pip3.6 install wolframalpha -q
pip3.6 install googlesearch-python -q
pip3.6 install pyowm -q
pip3.6 install pickle -q
pip3.6 install keras -q
pip3.6 install discord -q
pip3.6 install python-dotenv -q
pip3.6 install praw -q
